//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace butterflow_ui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("butterflow_ui.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 fps.
        /// </summary>
        public static string _120fpsLabel {
            get {
                return ResourceManager.GetString("_120fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 fps.
        /// </summary>
        public static string _24fpsLabel {
            get {
                return ResourceManager.GetString("_24fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x.
        /// </summary>
        public static string _2xLabel {
            get {
                return ResourceManager.GetString("_2xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 fps.
        /// </summary>
        public static string _30fpsLabel {
            get {
                return ResourceManager.GetString("_30fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x.
        /// </summary>
        public static string _3xLabel {
            get {
                return ResourceManager.GetString("_3xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x.
        /// </summary>
        public static string _4xLabel {
            get {
                return ResourceManager.GetString("_4xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 fps.
        /// </summary>
        public static string _60fpsLabel {
            get {
                return ResourceManager.GetString("_60fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butterflow on github....
        /// </summary>
        public static string AboutButterflowMenu {
            get {
                return ResourceManager.GetString("AboutButterflowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butterflow-ui on github....
        /// </summary>
        public static string AboutButterflowUIMenu {
            get {
                return ResourceManager.GetString("AboutButterflowUIMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About butterflow-ui.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buttterflow-ui is a graphical user interface for the butterflow video processor. .
        /// </summary>
        public static string AboutWindowDescription {
            get {
                return ResourceManager.GetString("AboutWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github.
        /// </summary>
        public static string AboutWindowGithubLinkLabel {
            get {
                return ResourceManager.GetString("AboutWindowGithubLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string AboutWindowLicenseLinkLabel {
            get {
                return ResourceManager.GetString("AboutWindowLicenseLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About butterflow-ui.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string AdvancedOptionsGroupBox {
            get {
                return ResourceManager.GetString("AdvancedOptionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current butterflow operation..
        /// </summary>
        public static string CancelTooltip {
            get {
                return ResourceManager.GetString("CancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip a subregion in the video..
        /// </summary>
        public static string ClipTooltip {
            get {
                return ResourceManager.GetString("ClipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Options.
        /// </summary>
        public static string CommonOptionsGroupBox {
            get {
                return ResourceManager.GetString("CommonOptionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy butterflow arguments.
        /// </summary>
        public static string CopyArgumentsMenu {
            get {
                return ResourceManager.GetString("CopyArgumentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rate.
        /// </summary>
        public static string CustomPlaybackRateLabel {
            get {
                return ResourceManager.GetString("CustomPlaybackRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers and Contributors.
        /// </summary>
        public static string DevelopersLabel {
            get {
                return ResourceManager.GetString("DevelopersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EndLabel {
            get {
                return ResourceManager.GetString("EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fast Pyramids.
        /// </summary>
        public static string FastPyramidsLabel {
            get {
                return ResourceManager.GetString("FastPyramidsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FastPyramidsTooltip {
            get {
                return ResourceManager.GetString("FastPyramidsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string FileInputGroupBox {
            get {
                return ResourceManager.GetString("FileInputGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        public static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string FileOutputGroupBox {
            get {
                return ResourceManager.GetString("FileOutputGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Filter.
        /// </summary>
        public static string FlowFilterLabel {
            get {
                return ResourceManager.GetString("FlowFilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter used for optical flow estimation..
        /// </summary>
        public static string FlowFilterTooltip {
            get {
                return ResourceManager.GetString("FlowFilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyramid iterations.
        /// </summary>
        public static string IterationsLabel {
            get {
                return ResourceManager.GetString("IterationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of iterations to use for each pyramid layer..
        /// </summary>
        public static string IterationsTooltip {
            get {
                return ResourceManager.GetString("IterationsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders the output video with the audio from the original video. In unchecked, no sound will be included in the output video..
        /// </summary>
        public static string KeepAudioDescription {
            get {
                return ResourceManager.GetString("KeepAudioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Audio.
        /// </summary>
        public static string KeepAudioLabel {
            get {
                return ResourceManager.GetString("KeepAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Subregions.
        /// </summary>
        public static string KeepSubregionsLabel {
            get {
                return ResourceManager.GetString("KeepSubregionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders subregions not explicitly specified..
        /// </summary>
        public static string KeepSubregionsTooltip {
            get {
                return ResourceManager.GetString("KeepSubregionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string LevelsLabel {
            get {
                return ResourceManager.GetString("LevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pyramid layers..
        /// </summary>
        public static string LevelsTooltip {
            get {
                return ResourceManager.GetString("LevelsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders the video without lossy compression. The video will not lose any visual quality, but it will result in a very large output file..
        /// </summary>
        public static string LosslessDescription {
            get {
                return ResourceManager.GetString("LosslessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless Quality.
        /// </summary>
        public static string LosslessLabel {
            get {
                return ResourceManager.GetString("LosslessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string OpenMenuItem {
            get {
                return ResourceManager.GetString("OpenMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Libraries.
        /// </summary>
        public static string OpenSourceCreditsLabel {
            get {
                return ResourceManager.GetString("OpenSourceCreditsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Options....
        /// </summary>
        public static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Changing the user language will require a restart of the program..
        /// </summary>
        public static string OptionsWindowLanguageChangeNotice {
            get {
                return ResourceManager.GetString("OptionsWindowLanguageChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Neighborhood.
        /// </summary>
        public static string PixelNeighborhoodLabel {
            get {
                return ResourceManager.GetString("PixelNeighborhoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the pixel neighborhood..
        /// </summary>
        public static string PixelNeighborhoodTooltip {
            get {
                return ResourceManager.GetString("PixelNeighborhoodTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the new framerate of the output video. This can be set in both absolute and relative terms..
        /// </summary>
        public static string PlaybackRateDescription {
            get {
                return ResourceManager.GetString("PlaybackRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Rate.
        /// </summary>
        public static string PlaybackRateLabel {
            get {
                return ResourceManager.GetString("PlaybackRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause the video..
        /// </summary>
        public static string PlayPauseTooltip {
            get {
                return ResourceManager.GetString("PlayPauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string ProcessLabel {
            get {
                return ResourceManager.GetString("ProcessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process the video. This may be a long process..
        /// </summary>
        public static string ProcessTooltip {
            get {
                return ResourceManager.GetString("ProcessTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyramid Scale Factor.
        /// </summary>
        public static string PyramidScaleLabel {
            get {
                return ResourceManager.GetString("PyramidScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PyramidScaleTooltip {
            get {
                return ResourceManager.GetString("PyramidScaleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Rendering.
        /// </summary>
        public static string RenderingLabel {
            get {
                return ResourceManager.GetString("RenderingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Resolution.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration _As....
        /// </summary>
        public static string SaveAsMenuItem {
            get {
                return ResourceManager.GetString("SaveAsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Configuration....
        /// </summary>
        public static string SaveMenuItem {
            get {
                return ResourceManager.GetString("SaveMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip backward in the video..
        /// </summary>
        public static string SkipBackTooltip {
            get {
                return ResourceManager.GetString("SkipBackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip forward in the video..
        /// </summary>
        public static string SkipForwardTooltip {
            get {
                return ResourceManager.GetString("SkipForwardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Derivative.
        /// </summary>
        public static string SmoothDerivativeLabel {
            get {
                return ResourceManager.GetString("SmoothDerivativeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the standard deviation used for smooth derivatives..
        /// </summary>
        public static string SmoothDerivativeTooltip {
            get {
                return ResourceManager.GetString("SmoothDerivativeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth Motion.
        /// </summary>
        public static string SmoothMotionLabel {
            get {
                return ResourceManager.GetString("SmoothMotionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to tune for smooth motion. This mode yields artifact-less frames by emphasizing blended frames over warping pixels..
        /// </summary>
        public static string SmoothMotionTooltip {
            get {
                return ResourceManager.GetString("SmoothMotionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the video..
        /// </summary>
        public static string StopTooltip {
            get {
                return ResourceManager.GetString("StopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual regions of the video to process..
        /// </summary>
        public static string SubregionsDescription {
            get {
                return ResourceManager.GetString("SubregionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subregions.
        /// </summary>
        public static string SubregionsLabel {
            get {
                return ResourceManager.GetString("SubregionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butterflow-ui.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To End.
        /// </summary>
        public static string ToEndLabel {
            get {
                return ResourceManager.GetString("ToEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSizeLabel {
            get {
                return ResourceManager.GetString("WindowSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WindowSizeTooltip {
            get {
                return ResourceManager.GetString("WindowSizeTooltip", resourceCulture);
            }
        }
    }
}
