//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace butterflow_ui.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("butterflow_ui.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 fps.
        /// </summary>
        public static string _120fpsLabel {
            get {
                return ResourceManager.GetString("_120fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 fps.
        /// </summary>
        public static string _24fpsLabel {
            get {
                return ResourceManager.GetString("_24fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x.
        /// </summary>
        public static string _2xLabel {
            get {
                return ResourceManager.GetString("_2xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 fps.
        /// </summary>
        public static string _30fpsLabel {
            get {
                return ResourceManager.GetString("_30fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x.
        /// </summary>
        public static string _3xLabel {
            get {
                return ResourceManager.GetString("_3xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x.
        /// </summary>
        public static string _4xLabel {
            get {
                return ResourceManager.GetString("_4xLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 fps.
        /// </summary>
        public static string _60fpsLabel {
            get {
                return ResourceManager.GetString("_60fpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about butterflow....
        /// </summary>
        public static string AboutButterflowMenu {
            get {
                return ResourceManager.GetString("AboutButterflowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about butterflow-ui....
        /// </summary>
        public static string AboutButterflowUIMenu {
            get {
                return ResourceManager.GetString("AboutButterflowUIMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About butterflow-ui.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options.
        /// </summary>
        public static string AdvancedOptionsGroupBox {
            get {
                return ResourceManager.GetString("AdvancedOptionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clip a subregion in the video..
        /// </summary>
        public static string ClipTooltip {
            get {
                return ResourceManager.GetString("ClipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Options.
        /// </summary>
        public static string CommonOptionsGroupBox {
            get {
                return ResourceManager.GetString("CommonOptionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Rate.
        /// </summary>
        public static string CustomPlaybackRateLabel {
            get {
                return ResourceManager.GetString("CustomPlaybackRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EndLabel {
            get {
                return ResourceManager.GetString("EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string FileInputGroupBox {
            get {
                return ResourceManager.GetString("FileInputGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        public static string FileLabel {
            get {
                return ResourceManager.GetString("FileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders the output video with the audio from the original video. In unchecked, no sound will be included in the output video..
        /// </summary>
        public static string KeepAudioDescription {
            get {
                return ResourceManager.GetString("KeepAudioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Audio.
        /// </summary>
        public static string KeepAudioLabel {
            get {
                return ResourceManager.GetString("KeepAudioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renders the video without lossy compression. The video will not lose any visual quality, but it will result in a very large output file..
        /// </summary>
        public static string LosslessDescription {
            get {
                return ResourceManager.GetString("LosslessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lossless Quality.
        /// </summary>
        public static string LosslessLabel {
            get {
                return ResourceManager.GetString("LosslessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the new framerate of the output video. This can be set in both absolute and relative terms..
        /// </summary>
        public static string PlaybackRateDescription {
            get {
                return ResourceManager.GetString("PlaybackRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback Rate.
        /// </summary>
        public static string PlaybackRateLabel {
            get {
                return ResourceManager.GetString("PlaybackRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause the video..
        /// </summary>
        public static string PlayPauseTooltip {
            get {
                return ResourceManager.GetString("PlayPauseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Rendering.
        /// </summary>
        public static string RenderingLabel {
            get {
                return ResourceManager.GetString("RenderingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Resolution.
        /// </summary>
        public static string ResolutionLabel {
            get {
                return ResourceManager.GetString("ResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip backward in the video..
        /// </summary>
        public static string SkipBackTooltip {
            get {
                return ResourceManager.GetString("SkipBackTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip forward in the video..
        /// </summary>
        public static string SkipForwardTooltip {
            get {
                return ResourceManager.GetString("SkipForwardTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the video..
        /// </summary>
        public static string StopTooltip {
            get {
                return ResourceManager.GetString("StopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual regions of the video to process..
        /// </summary>
        public static string SubregionsDescription {
            get {
                return ResourceManager.GetString("SubregionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subregions.
        /// </summary>
        public static string SubregionsLabel {
            get {
                return ResourceManager.GetString("SubregionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to butterflow-ui.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To End.
        /// </summary>
        public static string ToEndLabel {
            get {
                return ResourceManager.GetString("ToEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthLabel {
            get {
                return ResourceManager.GetString("WidthLabel", resourceCulture);
            }
        }
    }
}
